# Generated by Django 5.0 on 2025-08-13 12:38

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre descriptivo del rol', max_length=255, verbose_name='Nombre del Rol')),
                ('code', models.CharField(help_text='Código único del rol (ej: super_admin)', max_length=50, unique=True, verbose_name='Código del Rol')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del rol y sus responsabilidades', verbose_name='Descripción')),
                ('is_system', models.BooleanField(default=False, help_text='Los roles del sistema no pueden ser eliminados', verbose_name='Rol del Sistema')),
                ('is_active', models.BooleanField(default=True, help_text='Si el rol está activo en el sistema', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Rol',
                'verbose_name_plural': 'Roles',
                'db_table': 'authorization_roles',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Nombre descriptivo del permiso', max_length=255, verbose_name='Nombre del Permiso')),
                ('code', models.CharField(help_text='Formato: recurso.accion (ej: users.create)', max_length=100, unique=True, verbose_name='Código del Permiso')),
                ('description', models.TextField(blank=True, help_text='Descripción detallada del permiso', verbose_name='Descripción')),
                ('resource', models.CharField(help_text='Recurso al que aplica el permiso (users, reports, etc.)', max_length=50, verbose_name='Recurso')),
                ('action', models.CharField(help_text='Acción permitida (create, read, update, delete, etc.)', max_length=50, verbose_name='Acción')),
                ('is_active', models.BooleanField(default=True, help_text='Si el permiso está activo en el sistema', verbose_name='Activo')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de Creación')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Última Actualización')),
            ],
            options={
                'verbose_name': 'Permiso',
                'verbose_name_plural': 'Permisos',
                'db_table': 'authorization_permissions',
                'ordering': ['resource', 'action'],
                'indexes': [models.Index(fields=['code'], name='authorizati_code_a759f5_idx'), models.Index(fields=['resource', 'action'], name='authorizati_resourc_8bd77c_idx'), models.Index(fields=['is_active'], name='authorizati_is_acti_195b47_idx')],
            },
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('granted_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Asignación')),
                ('granted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='granted_role_permissions', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='permission_roles', to='authorization.permission', verbose_name='Permiso')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='authorization.role', verbose_name='Rol')),
            ],
            options={
                'verbose_name': 'Permiso de Rol',
                'verbose_name_plural': 'Permisos de Roles',
                'db_table': 'authorization_role_permissions',
            },
        ),
        migrations.AddField(
            model_name='role',
            name='permissions',
            field=models.ManyToManyField(related_name='roles', through='authorization.RolePermission', to='authorization.permission', verbose_name='Permisos'),
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('assigned_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha de Asignación')),
                ('is_active', models.BooleanField(default=True, help_text='Si el rol está activo para este usuario', verbose_name='Activo')),
                ('expires_at', models.DateTimeField(blank=True, help_text='Fecha opcional de expiración del rol', null=True, verbose_name='Fecha de Expiración')),
                ('assigned_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_user_roles', to=settings.AUTH_USER_MODEL, verbose_name='Asignado por')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_users', to='authorization.role', verbose_name='Rol')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
            options={
                'verbose_name': 'Rol de Usuario',
                'verbose_name_plural': 'Roles de Usuarios',
                'db_table': 'authorization_user_roles',
            },
        ),
        migrations.AddIndex(
            model_name='rolepermission',
            index=models.Index(fields=['role', 'permission'], name='authorizati_role_id_fea942_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='rolepermission',
            unique_together={('role', 'permission')},
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['code'], name='authorizati_code_45cd00_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_active'], name='authorizati_is_acti_377d9c_idx'),
        ),
        migrations.AddIndex(
            model_name='role',
            index=models.Index(fields=['is_system'], name='authorizati_is_syst_327daf_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user', 'is_active'], name='authorizati_user_id_dd400e_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role', 'is_active'], name='authorizati_role_id_48adcf_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['expires_at'], name='authorizati_expires_bd4f17_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
    ]
