# Generated by Django 5.0 on 2025-08-13 19:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="location",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the record was soft deleted.",
                null=True,
                verbose_name="deleted at",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who soft deleted this record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="deleted by",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this record should be treated as active.",
                verbose_name="active",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="deleted_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Date and time when the record was soft deleted.",
                null=True,
                verbose_name="deleted at",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="User who soft deleted this record.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted",
                to=settings.AUTH_USER_MODEL,
                verbose_name="deleted by",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Designates whether this record should be treated as active.",
                verbose_name="active",
            ),
        ),
    ]
