# Generated by Django 5.0 on 2025-08-13 19:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0003_sectortemplate_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLog",
            fields=[
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True,
                        help_text="Date and time when the record was created.",
                        verbose_name="created at",
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(
                        auto_now=True,
                        help_text="Date and time when the record was last updated.",
                        verbose_name="updated at",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        help_text="Unique identifier for the record.",
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="Date and time when the record was soft deleted.",
                        null=True,
                        verbose_name="deleted at",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this record should be treated as active.",
                        verbose_name="active",
                    ),
                ),
                (
                    "table_name",
                    models.CharField(
                        help_text="Nombre de la tabla afectada.",
                        max_length=100,
                        verbose_name="nombre de tabla",
                    ),
                ),
                (
                    "record_id",
                    models.CharField(
                        help_text="ID del registro afectado.",
                        max_length=36,
                        verbose_name="ID del registro",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("CREATE", "Crear"),
                            ("UPDATE", "Actualizar"),
                            ("DELETE", "Eliminar"),
                            ("ROLLBACK", "Rollback"),
                        ],
                        help_text="Tipo de acción realizada.",
                        max_length=10,
                        verbose_name="acción",
                    ),
                ),
                (
                    "old_values",
                    models.JSONField(
                        blank=True,
                        help_text="Valores de los campos antes del cambio.",
                        null=True,
                        verbose_name="valores anteriores",
                    ),
                ),
                (
                    "new_values",
                    models.JSONField(
                        blank=True,
                        help_text="Valores de los campos después del cambio.",
                        null=True,
                        verbose_name="valores nuevos",
                    ),
                ),
                (
                    "changed_fields",
                    models.JSONField(
                        blank=True,
                        help_text="Lista de campos que fueron modificados.",
                        null=True,
                        verbose_name="campos modificados",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True,
                        help_text="Dirección IP desde donde se realizó el cambio.",
                        null=True,
                        verbose_name="dirección IP",
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        blank=True,
                        help_text="User agent del navegador utilizado.",
                        null=True,
                        verbose_name="user agent",
                    ),
                ),
                (
                    "session_key",
                    models.CharField(
                        blank=True,
                        help_text="Clave de la sesión del usuario.",
                        max_length=40,
                        null=True,
                        verbose_name="clave de sesión",
                    ),
                ),
                (
                    "reason",
                    models.TextField(
                        blank=True,
                        help_text="Razón o comentario sobre el cambio realizado.",
                        null=True,
                        verbose_name="razón del cambio",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who created this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_created",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="created by",
                    ),
                ),
                (
                    "deleted_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who soft deleted this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_deleted",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="deleted by",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        help_text="User who last updated this record.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="%(class)s_updated",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="updated by",
                    ),
                ),
            ],
            options={
                "verbose_name": "log de auditoría",
                "verbose_name_plural": "logs de auditoría",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["table_name", "record_id"],
                        name="organizatio_table_n_179f78_idx",
                    ),
                    models.Index(
                        fields=["action"], name="organizatio_action_ccad07_idx"
                    ),
                    models.Index(
                        fields=["created_at"], name="organizatio_created_2196ef_idx"
                    ),
                    models.Index(
                        fields=["created_by"], name="organizatio_created_ab31de_idx"
                    ),
                ],
            },
        ),
    ]
