# Generated by Django 5.0 on 2025-08-14 02:45

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0004_auditlog"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="location",
            name="unique_main_location_per_organization",
        ),
        migrations.AlterField(
            model_name="organization",
            name="nit",
            field=models.CharField(
                help_text="Número de Identificación Tributaria sin dígito de verificación.",
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="NIT debe tener formato válido: 123456789 o 123-456-789",
                        regex="^[\\d\\-]{9,15}$",
                    )
                ],
                verbose_name="NIT",
            ),
        ),
        migrations.AddConstraint(
            model_name="location",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("es_principal", True), ("deleted_at__isnull", True)
                ),
                fields=("organization",),
                name="unique_main_location_per_organization",
            ),
        ),
    ]
