# Generated by Django 5.0 on 2025-08-17 05:30

import apps.organization.models
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0008_sedeprestadora_sedeservicio_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="healthorganization",
            name="alertas_activas",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Número de alertas SOGCS activas pendientes de atención.",
                verbose_name="alertas SOGCS activas",
            ),
        ),
        migrations.AddField(
            model_name="healthorganization",
            name="coordinador_calidad",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario designado como coordinador de calidad SOGCS.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="health_orgs_as_quality_coordinator",
                to=settings.AUTH_USER_MODEL,
                verbose_name="coordinador de calidad",
            ),
        ),
        migrations.AddField(
            model_name="healthorganization",
            name="estado_pamec",
            field=models.CharField(
                choices=[
                    ("no_iniciado", "No Iniciado"),
                    ("en_configuracion", "En Configuración"),
                    ("activo", "Activo"),
                    ("suspendido", "Suspendido"),
                ],
                default="no_iniciado",
                help_text="Estado del Programa de Auditoría para el Mejoramiento de la Calidad.",
                max_length=20,
                verbose_name="estado PAMEC",
            ),
        ),
        migrations.AddField(
            model_name="healthorganization",
            name="estado_sic",
            field=models.CharField(
                choices=[
                    ("no_iniciado", "No Iniciado"),
                    ("en_configuracion", "En Configuración"),
                    ("activo", "Activo"),
                    ("atrasado", "Atrasado"),
                ],
                default="no_iniciado",
                help_text="Estado del Sistema de Información para la Calidad.",
                max_length=20,
                verbose_name="estado SIC",
            ),
        ),
        migrations.AddField(
            model_name="healthorganization",
            name="estado_sua",
            field=models.CharField(
                choices=[
                    ("no_aplica", "No Aplica"),
                    ("interesado", "Interesado"),
                    ("en_proceso", "En Proceso"),
                    ("acreditado", "Acreditado"),
                    ("vencido", "Vencido"),
                ],
                default="no_aplica",
                help_text="Estado del Sistema Único de Acreditación.",
                max_length=20,
                verbose_name="estado SUA",
            ),
        ),
        migrations.AddField(
            model_name="healthorganization",
            name="estado_suh",
            field=models.CharField(
                choices=[
                    ("no_iniciado", "No Iniciado"),
                    ("en_configuracion", "En Configuración"),
                    ("autoevaluacion", "En Autoevaluación"),
                    ("mejoramiento", "Plan de Mejoramiento"),
                    ("habilitado", "Habilitado"),
                    ("suspendido", "Suspendido"),
                ],
                default="no_iniciado",
                help_text="Estado actual del Sistema Único de Habilitación.",
                max_length=20,
                verbose_name="estado SUH",
            ),
        ),
        migrations.AddField(
            model_name="healthorganization",
            name="fecha_activacion_sogcs",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora de activación del módulo SOGCS.",
                null=True,
                verbose_name="fecha activación SOGCS",
            ),
        ),
        migrations.AddField(
            model_name="healthorganization",
            name="fecha_proxima_auditoria",
            field=models.DateField(
                blank=True,
                help_text="Fecha programada para la próxima auditoría PAMEC.",
                null=True,
                verbose_name="fecha próxima auditoría",
            ),
        ),
        migrations.AddField(
            model_name="healthorganization",
            name="fecha_ultima_autoevaluacion",
            field=models.DateField(
                blank=True,
                help_text="Fecha de la última autoevaluación SUH realizada.",
                null=True,
                verbose_name="fecha última autoevaluación",
            ),
        ),
        migrations.AddField(
            model_name="healthorganization",
            name="notificaciones_habilitadas",
            field=models.BooleanField(
                default=True,
                help_text="Indica si las notificaciones SOGCS están habilitadas.",
                verbose_name="notificaciones habilitadas",
            ),
        ),
        migrations.AddField(
            model_name="healthorganization",
            name="pamec_procesos_auditoria",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Número de procesos incluidos en el programa PAMEC.",
                verbose_name="procesos en auditoría PAMEC",
            ),
        ),
        migrations.AddField(
            model_name="healthorganization",
            name="porcentaje_cumplimiento_pamec",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Porcentaje de cumplimiento actual del PAMEC (0.00-100.00).",
                max_digits=5,
                null=True,
                verbose_name="porcentaje cumplimiento PAMEC",
            ),
        ),
        migrations.AddField(
            model_name="healthorganization",
            name="porcentaje_cumplimiento_sic",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Porcentaje de cumplimiento actual del SIC (0.00-100.00).",
                max_digits=5,
                null=True,
                verbose_name="porcentaje cumplimiento SIC",
            ),
        ),
        migrations.AddField(
            model_name="healthorganization",
            name="porcentaje_cumplimiento_suh",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Porcentaje de cumplimiento actual del SUH (0.00-100.00).",
                max_digits=5,
                null=True,
                verbose_name="porcentaje cumplimiento SUH",
            ),
        ),
        migrations.AddField(
            model_name="healthorganization",
            name="responsable_habilitacion",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario responsable del proceso de habilitación SUH.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="health_orgs_as_habilitation_responsible",
                to=settings.AUTH_USER_MODEL,
                verbose_name="responsable de habilitación",
            ),
        ),
        migrations.AddField(
            model_name="healthorganization",
            name="sic_indicadores_activos",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Número de indicadores de calidad activos en SIC.",
                verbose_name="indicadores activos SIC",
            ),
        ),
        migrations.AddField(
            model_name="healthorganization",
            name="sogcs_configuration",
            field=models.JSONField(
                blank=True,
                help_text="Configuración JSON del Sistema Obligatorio de Garantía de Calidad en Salud.",
                null=True,
                verbose_name="configuración SOGCS",
            ),
        ),
        migrations.AddField(
            model_name="healthorganization",
            name="sogcs_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Indica si el módulo SOGCS está habilitado para esta institución.",
                verbose_name="SOGCS habilitado",
            ),
        ),
        migrations.AddField(
            model_name="healthorganization",
            name="suh_servicios_habilitados",
            field=models.PositiveIntegerField(
                default=0,
                help_text="Número total de servicios habilitados bajo SUH.",
                verbose_name="servicios habilitados SUH",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="codigo_departamento",
            field=models.CharField(
                blank=True,
                help_text="Código DIVIPOLA del departamento (ej: 11 para Bogotá D.C.)",
                max_length=2,
                verbose_name="código departamento DIVIPOLA",
            ),
        ),
        migrations.AddField(
            model_name="location",
            name="codigo_municipio",
            field=models.CharField(
                blank=True,
                help_text="Código DIVIPOLA del municipio (ej: 11001 para Bogotá)",
                max_length=5,
                verbose_name="código municipio DIVIPOLA",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="enabled_modules",
            field=models.TextField(
                default="{}",
                help_text="Módulos habilitados para la organización en formato JSON.",
                verbose_name="módulos habilitados",
            ),
        ),
        migrations.AddField(
            model_name="organization",
            name="sector_config",
            field=models.TextField(
                default="{}",
                help_text="Configuración específica del sector en formato JSON.",
                verbose_name="configuración del sector",
            ),
        ),
        migrations.AlterField(
            model_name="organization",
            name="logo",
            field=models.ImageField(
                blank=True,
                help_text="Logo oficial de la organización. Máximo 2MB, formatos: JPG, PNG, GIF, WebP.",
                null=True,
                upload_to=apps.organization.models.get_logo_upload_path,
                validators=[apps.organization.models.validate_logo],
                verbose_name="logo",
            ),
        ),
        migrations.AddIndex(
            model_name="healthorganization",
            index=models.Index(
                fields=["sogcs_enabled"], name="organizatio_sogcs_e_9a715a_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthorganization",
            index=models.Index(
                fields=["estado_suh"], name="organizatio_estado__d55b6c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthorganization",
            index=models.Index(
                fields=["estado_pamec"], name="organizatio_estado__1dfe07_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthorganization",
            index=models.Index(
                fields=["estado_sic"], name="organizatio_estado__f9c52b_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthorganization",
            index=models.Index(
                fields=["estado_sua"], name="organizatio_estado__6215c0_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthorganization",
            index=models.Index(
                fields=["coordinador_calidad"], name="organizatio_coordin_f73c02_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthorganization",
            index=models.Index(
                fields=["responsable_habilitacion"],
                name="organizatio_respons_7badcd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="healthorganization",
            index=models.Index(
                fields=["fecha_activacion_sogcs"], name="organizatio_fecha_a_5f2cdb_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="healthorganization",
            index=models.Index(
                fields=["fecha_ultima_autoevaluacion"],
                name="organizatio_fecha_u_27908a_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="healthorganization",
            index=models.Index(
                fields=["fecha_proxima_auditoria"],
                name="organizatio_fecha_p_b9d5af_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="healthorganization",
            index=models.Index(
                fields=["sogcs_enabled", "estado_suh"],
                name="organizatio_sogcs_e_d0c91f_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="healthorganization",
            index=models.Index(
                fields=["sogcs_enabled", "estado_pamec"],
                name="organizatio_sogcs_e_5f20b9_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="healthorganization",
            index=models.Index(
                fields=["sogcs_enabled", "alertas_activas"],
                name="organizatio_sogcs_e_361fdd_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["codigo_departamento"], name="organizatio_codigo__1c475c_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="location",
            index=models.Index(
                fields=["codigo_municipio"], name="organizatio_codigo__92ae63_idx"
            ),
        ),
    ]
