# Generated by Django 5.0 on 2025-08-18 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0009_healthorganization_alertas_activas_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="email_contacto",
            field=models.EmailField(
                blank=True,
                help_text="Email principal de contacto de la organización.",
                max_length=254,
                null=True,
                verbose_name="email de contacto",
            ),
        ),
    ]
