# Generated by Django 5.0 on 2025-08-18 01:37

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0010_alter_organization_email_contacto"),
    ]

    operations = [
        migrations.AlterField(
            model_name="organization",
            name="telefono_principal",
            field=models.CharField(
                blank=True,
                help_text="Teléfono principal de contacto.",
                max_length=15,
                null=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Número de teléfono debe tener un formato válido.",
                        regex="^\\+?[\\d\\s\\-\\(\\)]{7,15}$",
                    )
                ],
                verbose_name="teléfono principal",
            ),
        ),
    ]
