# Generated by Django 5.0 on 2025-08-23 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("organization", "0013_add_health_services"),
    ]

    operations = [
        migrations.AddField(
            model_name="serviceimportlog",
            name="message",
            field=models.TextField(
                blank=True,
                help_text="Mensaje de resumen de la importación",
                verbose_name="mensaje",
            ),
        ),
    ]
