# Generated by Django 5.0 on 2025-08-18 15:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("sogcs", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="headquarterlocation",
            name="created_by",
        ),
        migrations.RemoveField(
            model_name="headquarterlocation",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="headquarterlocation",
            name="updated_by",
        ),
        migrations.DeleteModel(
            name="EnabledHealthService",
        ),
        migrations.DeleteModel(
            name="HeadquarterLocation",
        ),
    ]
